arayApp.exe:arrayImp.o arrayApp.o mylib.o
	g++ -o arrayApp.exe  arrayApp.o arrayImp.o mylib.o
arrayImp.o:arrayImp.cpp
	g++ -c arrayImp.cpp
arrayApp.o:arrayApp.cpp
	g++ -c arrayApp.cpp
mylib.o:mylib.cpp
	g++ -c mylib.cpp

