operation.exe: operationimp.o operationapp.o
	cc -o operation.exe operationimp.o operationapp.o
operationimp.o: operationimp.c
	cc -c operationimp.c
operationapp.o: operationapp.c
	cc -c operationapp.c

