libapp.exe: libapp.o numericimp.o arrayimp.o
	g++ -o libapp.exe libapp.o numericimp.o arrayimp.o
libapp.o: libapp.cpp
	g++ -c libapp.cpp
numericimp.o: numericimp.cpp
	g++ -c numericimp.cpp
arrayimp.o: arrayimp.cpp
	g++ -c arrayimp.cpp
