app.exe:Cloth.o Material.o app.o
	g++ -o app.exe app.o Cloth.o Material.o
Cloth.o:Cloth.cpp
	g++ -c Cloth.cpp
Material.o:Material.cpp
	g++ -c Material.cpp
app.o:app.cpp
	g++ -c app.cpp
                                                                                                                             
       
