queueApp.exe: queueApp.o queueImp.o myLib.o
	g++ -o queueApp.exe  queueApp.o queueImp.o myLib.o
queueImp.o: queueImp.cpp
	g++ -c queueImp.cpp
queueApp.o: queueApp.cpp
	g++ -c queueApp.cpp
myLib.o: myLib.cpp
	g++ -c myLib.cpp
		

