treeApp.exe:  treeApp.o treeImp.o mylib.o
	g++ -o treeApp.exe treeApp.o treeImp.o mylib.o
treeImp.o: treeImp.cpp
	g++ -c treeImp.cpp
treeApp.o: treeApp.cpp
	g++ -c treeApp.cpp
mylib.o:mylib.cpp
	g++ -c mylib.cpp

