linkedApp.exe: linkedApp.o linkedImp.o mylib.o
	g++ -o linkedApp.exe linkedApp.o linkedImp.o mylib.o
linkedApp.o: linkedApp.cpp
	g++ -c linkedApp.cpp
linkedImp.o: linkedImp.cpp
	g++ -c linkedImp.cpp
mylib.o: mylib.cpp
	g++ -c mylib.cpp


