libapp.exe:sortimp.o reverseimp.o libapp.o
	g++ -o libapp.exe  libapp.o sortimp.o reverseimp.o
sortimp.o:sortimp.cpp
	g++ -c sortimp.cpp 
reverseimp.o:reverseimp.cpp
	g++ -c reverseimp.cpp
libapp.o:libapp.cpp
	g++ -c libapp.cpp
