listApp.exe: listApp.o listImp.o mylib.o
	g++ -o listApp.exe listApp.o listImp.o mylib.o
listImp.o: listImp.cpp
	g++ -c listImp.cpp
listApp.o: listApp.cpp
	g++ -c listApp.cpp
mylib.o: mylib.cpp
	g++ -c mylib.cpp


